### ISSUE TITLE
max_vars(7) don't generate a solution with variable G

### ISSUE THREAD

**Issue by hakank** [logic-and-learning-lab/Popper#14]
Here is a problem where Popper don't generate/test the combination that should be the solution, or more specific: the variable `G` is not generated even though `max_vars` is set to 7.

The setup is to solve the following puzzle:
```
1 + 4 = 5
2 + 5 = 12
3 + 6 = 21
5 + 8 = ??
```
(A variant that works as expected is here: http://hakank.org/popper/facebook_puzzle/ ).

In this variant the problem is represented by a 6 arity predicate `f(A,B,C,D,E,F)` with these positive examples:
```
%% exs.pl
%% pos(f( A, B, C, D, E, F)).
pos(f( 0, 0, 0, 1, 4, 5)).
pos(f( 1, 4, 5, 2, 5,12)).
pos(f( 2, 5,12, 3, 6,21)).
```

There are several answers to the puzzle, but I'm now looking for the solution where `??` is 34 by the following
```
F = C + D + E   % 21 + 5 + 8 = 34
```

This should be - unless I'm missing something - the predicate
```
f(A,B,C,D,E,F) :- plus(C,D,G), plus(E,G,F).
```

But Popper don't find this - or any - solution. Here's the encoding.

The BK as 
```
%% bk.pl
plus(X,Y,Z) :-
        integer(X),
        integer(Y),
        Z is X + Y.

%% Also tested this:
%% :- use_module(library(clpfd)).
%% plus(X,Y,Z) :- 
%%      Z #= X + Y.
%%
```

and the bias as:
```
%% bias.pl
max_vars(7).
max_body(2).
max_clauses(1).

head_pred(f,6).
body_pred(plus,3).
```

Popper generates 360 programs, but does not generate the candidate predicate `plus(C,D,G)`. In fact, it doesn't generate any solution with the variable `G`. Given that `max_vars` allow 7 variables, I had expected that Popper should try some program with variable `G`. 

Have I missed how `max_vars/1` works?

Interestingly, when changing to `max_body(3)` (from `max_body(2)`), then there are several candidate programs that includes the variable `G` for bodies with 3 predicates, but no solution is found (with a timeout 45 minutes and over 65 000 generated programs).

**Comment by andrewcropper** [comment]
Your understanding is correct.

The issue is with two of Popper's implicit biases:

1. Every variable in the head of a rule must also appear in the body
2. Every variable must appear at least twice in a rule

If I remove these biases, Popper learns this solution in 0.842s:

f(A,B,C,D,E,F):- plus(A,C,G).

I will add user options to disable these biases. Both biases are, however, generally helpful to prune the search space and to learn more meaningful programs, so I am unsure whether they should be enabled by default.

**Comment by hakank** [comment]
@andrewcropper  Thanks for the explanation and adding the flags. 

However, the specific solution `plus(A,C,G)` is a bit strange since it don't bind `G` at all. Instead it should be something like `plus(C,D,G), plus(E,G,F).`. In this case the second implicit bias should be active. But I'll play with the flags and see....

**Comment by andrewcropper** [comment]
@hakank I have added an `allow_singletons.` flag to Popper (e894d2ee26e7b89c1971e827d675935eff0f4ead). For the Facebook puzzle you shared, Popper now learns this solution:
```prolog
f(A,B,C):-mult(B,A,D),plus(A,D,C).
```

**Comment by hakank** [comment]
Thanks for the addition of the flags, Andrew.

However, the version of this puzzle that I had problem with was not with `f/3` version of the problem. Popper already solves the problem with the solution
```
f(A,B,C):-mult(A,B,D),plus(A,D,C).
```

The version that I had problem with was rather the `f/6` variant of the puzzle were the solution should be something like: 
```
f(A,B,C,D,E,F) :- plus(C,D,G), plus(E,G,F).
```
I.e. that Popper should ignore `A` and `B` and "create" the variable `G`.

I tested to add the new flags but don't get any proper solution.

With both `allow_singleton` and `non_datalog`, the following (nonsensical) solution is shown:
```
% BEST PROG 20:
f(A,B,C,D,E,F):-plus(A,B,G).
% Precision:1.00, Recall:1.00, TP:3, FN:0, TN:0, FP:0
```

It is trivially true, but not really the solution of the problem.

**Comment by andrewcropper** [comment]
The larger solution should be in the hypothesis space.

However, if there are no examples that refute the simpler hypothesis, Popper will simply return it.

I am unsure what else we can do.

**Comment by hakank** [comment]
You don't have to do anything more.  :-) 

Your answer inspired me to add a neg example to remove that strange solution:
```
neg(f( 2, 5,12, 3, 6,7)). 
```

Now Popper finds this correct solution:
```
% BEST PROG 21:
f(A,B,C,D,E,F):-plus(E,D,G),plus(C,G,F).
% Precision:1.00, Recall:1.00, TP:3, FN:0, TN:1, FP:0
```

Testing in SWI-Prolog:
```
$ swipl
?- use_module(library(clpfd)).
?- [user].
|: plus(X,Y,Z) :-
|:         integer(X),
|:         integer(Y),
|:         Z #= X + Y.
|: f(A,B,C,D,E,F):-plus(E,D,G),plus(C,G,F).
|: ^D% user://1 compiled 0.00 sec, 1 clauses
true.

?- f(3,6,21,5,8,F).
F = 34.
```


(I had to use both `allow`singletons` and `non_datalog` for this.)

The full example is here: http://hakank.org/popper/facebook_puzzle2/

Thanks!

**Comment by andrewcropper** [comment]
Thank you for confirming!
