### ISSUE TITLE
example/reverse/exs.pl includes the lines of the solution

### ISSUE THREAD

**Issue by hakank** [logic-and-learning-lab/Popper#15]
The file `example/reverse/exs.pl` includes the solution of the problem, i.e.
```
f(A,B):-empty(A),empty(B).
f(A,B):-head(A,C),tail(A,D),f(D,E),my_append(E,C,B).
```

which makes Prolog to complain about `No permission to modify static procedure 'f/2'`.

**Comment by andrewcropper** [comment]
Fixed. Thanks for spotting it!
