### ISSUE TITLE
Generating all solutions

### ISSUE THREAD

**Issue by hakank** [logic-and-learning-lab/Popper#16]
When solving problems with Constraint Programming, I'm often looking for all solutions, or at least checking if there are more than one solution. So I wondered if this is possible in Popper as well.

Here is a simple way to do that (in popper.py):
```
diff --git a/popper.py b/popper.py
index 325f533..a36ee1a 100755
--- a/popper.py
+++ b/popper.py
@@ -49,7 +49,7 @@ def popper(experiment):
             # 2. Test
             with experiment.duration('test'):
                 (outcome, (TP,FN,TN,FP)) = tester.test(program)
-
+                
             if experiment.debug:
                 print(f'Program {experiment.total_programs}:')
                 pprint(program)
@@ -64,7 +64,8 @@ def popper(experiment):
                     experiment.show_stats(True)
                 print('SOLUTION:')
                 pprint(program)
-                return
+                outcome = (Outcome.NONE,Outcome.NONE)
+                # return
```

The alternative solutions are not unique, since it's a lot of symmetries (renaming variables etc) and there might be nonsensical/whimsical solutions. For examples here are some of the first solutions for `examples/robots-functional`:
```
SOLUTION:
f(A,B):- move_up(A,B).
f(A,B):- move_up(A,C),f(C,B).
SOLUTION:
f(A,B):- move_left(A,C),move_right(C,B).
f(A,B):- move_up(A,C),f(C,B).
SOLUTION:
f(A,B):- move_down(A,C),move_up(C,B).
f(A,B):- move_up(A,C),f(C,B).
SOLUTION:
f(A,B):- move_up(A,C),move_up(C,B).
f(A,B):- move_up(A,C),f(C,B).
SOLUTION:
f(A,B):- move_right(A,C),move_left(C,B).
f(A,B):- move_up(A,C),f(C,B).
SOLUTION:
f(A,B):- move_left(A,C),move_right(C,D),move_up(D,B).
f(A,B):- move_up(A,C),f(C,B).
...
```

And we now know that this is the only solution (given the bias parameters) for http://hakank.org/popper/member/:
```
SOLUTION:
mem(A,B):- head(B,A).
mem(A,B):- tail(B,C),mem(A,C).
NO SOLUTION
```

I'm not sure how useful this is for the general Popper user, but I think it's a great feature, for example to see if there are any interesting alternative solutions or fine tune the decoding.

**Comment by andrewcropper** [comment]
I have added the ability for Popper to return multiple solutions with a `--max-solutions` flag. #17

**Comment by hakank** [comment]
Just a note that --max-solutions is now commented away.
