### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by JackWahlig** [logic-and-learning-lab/Popper#26]
Windows does not allow the use of singal.SIGALRM when enforcing timeout. Would need to be changed in order to allow Window's users to run Popper.

https://github.com/logic-and-learning-lab/Popper/blob/4611db53a7f5c977c39d4ff002e7039b0ecf129b/popper/util.py#L44

**Comment by rtaupe** [comment]
Is this issue supposed to be fixed?
I'd also like to use Popper on Windows and I'm still getting the following error:
> $ python popper.py examples/dropk
> Traceback (most recent call last):
>   File "C:\data\repos\github.com\logic-and-learning-lab\Popper\popper.py", line 8, in <module>
>     prog, score, stats = learn_solution(settings)
>   File "C:\data\repos\github.com\logic-and-learning-lab\Popper\popper\loop.py", line 414, in learn_solution
>     timeout(settings, popper, (settings,), timeout_duration=int(settings.timeout),)
>   File "C:\data\repos\github.com\logic-and-learning-lab\Popper\popper\util.py", line 51, in timeout
>     signal.signal(signal.SIGALRM, handler)
> AttributeError: module 'signal' has no attribute 'SIGALRM'. Did you mean: 'SIGABRT'?
