### ISSUE TITLE
Partial directions

### ISSUE THREAD

**Issue by celinehocquette** [logic-and-learning-lab/Popper#31]
Popper currently does not support partial directions in the bias file. All or none of the directions must be provided, providing only some of them might result in failure to find a solution.

For examples, adding the following directions to the minimal decay example prevents to find any model:

```
%direction(next_value,(in,out)).
direction(does,(in,out,out)).
direction(my_true_value,(in,out)).
direction(my_succ,(out,out)).
direction(c_pressButton,(in,)).
direction(c_noop,(in,)).
direction(c_player,(in,)).
direction(c1,(in,)).
direction(c2,(in,)).
direction(c3,(in,)).
direction(c4,(in,)).
direction(c5,(in,)).
```

**Comment by andrewcropper** [comment]
Unsure how to properly fix. I have added a warning to Popper to check that all directions are given.
