### ISSUE TITLE
Usage of the extra bias for specifing the clause

### ISSUE THREAD

**Issue by yangdinglou** [logic-and-learning-lab/Popper#37]
Hello. I want to define some more specific properties in the bias file. I learned from the file _alan.pl_, but things don't work as I guess. For instance, I want to make sure that

- Two clauses.
- Only one of them contains the predicate _q_ in the body.

So I write the following things in the _bias.pl_.
```
:-
    not clause(1).

:-
    head_literal(1,_,_,_), %%allowing the 0 clause to contain q.
    body_literal(_,q,_,_).

```
But the result seems to show that neither of them contains _q_ predicate. Obviously, the second clause I write makes it failed, but what is the reason? And is there a way to express what I want to restrict?

Thank you.

**Comment by andrewcropper** [comment]
> 	• Only one of them contains the predicate q in the body.

This constraint should work:

:-
	body_literal(Rule1,q,_,_),
	body_literal(Rule2,q,_,_),
	Rule1 != Rule2.

This constraint prohibits two different rules from having the body literal q. 

Does that help?

**Comment by yangdinglou** [comment]
Thanks, it helps a lot. I got the reason.
