### ISSUE TITLE
The reason to force ordering in predicate invention?

### ISSUE THREAD

**Issue by yangdinglou** [logic-and-learning-lab/Popper#38]
Hello,

I find the current code forbids the learning of mutual recursive predicates by "force ordering" in the `alan.pl`.
https://github.com/logic-and-learning-lab/Popper/blob/91256b27005aacba9b84a2358697de522c109683/popper/lp/alan.pl#L591

I don't get the reason for adding it, and some learning can be done if removing the restriction. Could you tell me something about that?

BTW, may I know the status of the issue https://github.com/logic-and-learning-lab/Popper/issues/25? Has the bug been located? Currently, I am using some tricks to skip the direction. (As in issue https://github.com/logic-and-learning-lab/Popper/issues/36, I use the `ground` predicate rather than the direction, and run multiple instances of learning. The correct one can be learned if lucky enough.) I would appreciate it if you can offer some details of the bug.

**Comment by fnakas** [comment]
Hello, I see this issue is closed but - if I am not mistaken - predicate invention is still not compatible with directions. Has it been decided that this will not be supported? Thank you!

**Comment by andrewcropper** [comment]
Hi,

Yes, PI is still incompatible with directions. It will eventually be supported, but it is, unfortunately, very low on my priority list.

Kind regards,

Andrew
