### ISSUE TITLE
Add description to the examples

### ISSUE THREAD

**Issue by hakank** [logic-and-learning-lab/Popper#42]
It would be great if the examples contains a description of the example. In earlier versions of Popper, most examples was quite clear (to me), but some of the newer iggp-* examples are not that clear.

The examples are surely described a little more in some of the Popper papers, but a (perhaps short) description would clarify what problem the example is solving.

**Comment by andrewcropper** [comment]
I've started to (finally) do this. Will keep it in mind in the future, thanks!
