### ISSUE TITLE
Too many stacked strings

### ISSUE THREAD

**Issue by andrewcropper** [logic-and-learning-lab/Popper#5]
When running the minimal decay problem, there is the exception:

```
[FATAL ERROR: at Wed Apr 21 09:44:38 2021
    Too many stacked strings]
```

This error is to do with pyswip. I can replicate it. It does not happen with pylo2.  We will therefore migrate from pswip to pylo2.

**Comment by andrewcropper** [comment]
Fixed

**Comment by andrewcropper** [comment]
Fixed with commit #45db7fe3faaea897b909845310dcd1ff958dc71f

**Comment by andrewcropper** [comment]
Not fixed. @hakan has found many cases of the problem: http://hakank.org/popper/

**Comment by rolfmorel** [comment]
This (https://github.com/yuce/pyswip/issues/102) and this (https://github.com/SWI-Prolog/swipl-devel/issues/660) suggest that it has been fixed on `master` of pyswip.

We could try this out some time, but in general we would need to wait for a new release of pyswip.

**Comment by hakank** [comment]
@rolfmorel  I installed the `master` of `pyswip`, and it surely look promising. Using the `pip` version, Popper stops with the "Too many stacked strings" error after about 25000-35000 generated programs. Running the `master` version I've had sessions which have generated over 450 000 programs without any complaints.

**Comment by hakank** [comment]
Further check with pyswip master branch.

I've now run all the instances above with a timeout of 1hour. No program failed with some strange error, but - unfortunately - all timed out (except for droplasts which found a bad solution). Also, I tested all my other problems as well as Popper examples and found no strange error, unexpected solutions or too much divergence in solving times.

**Comment by rolfmorel** [comment]
For future reference: applying the changes from this pull request on top of pyswip 0.2.10 fixes this issue for me: https://github.com/yuce/pyswip/pull/103/files

(Note that just using the master branch of pyswip does not seem to work for me as the API seems to have (subtly) changed.)
