### ISSUE TITLE
Learning more than one head.

### ISSUE THREAD

**Issue by pudumagico** [logic-and-learning-lab/Popper#52]
Is it possible?

**Comment by pudumagico** [comment]
Thanks @celinehocquette! 
Although I was thinking of learning some auxiliary head rules that would be used to learn a 'final' head rule.
Is that possible? I have only seen examples with only one 'head_pred'.

**Comment by celinehocquette** [comment]
It is possible to learn auxiliary predicates through predicate invention. Two examples are available [here](https://github.com/logic-and-learning-lab/Popper/tree/main/examples/kinship-pi) and [here](https://github.com/logic-and-learning-lab/Popper/tree/main/examples/robots-pi). In short, you must use 'enable_pi.' in your bias file.
In this case, Popper is allowed to define new head predicates which will be used in the learned program.

**Comment by andrewcropper** [comment]
@pudumagico Popper cannot currently learn programs with different head user-defined head predicate symbols, i.e. multiple `head_pred` declarations. However, it is something we could implement relatively easily. I'll add it as a todo.
