### ISSUE TITLE
"PL_put_chars: Assertion failed: 0" probably due to an automatic upgrade of swi-prolog

### ISSUE THREAD

**Issue by ramparany** [logic-and-learning-lab/Popper#56]
Hi,

my Popper code now crashes with the error "PL_put_chars: Assertion failed: 0" .  I suspect the pyswip module and its dependency to swi-prolog, which I think has been automatically upgraded on my ubuntu PC. This python script  fails with the same error:
from pyswip import Prolog
prolog = Prolog()
prolog.assertz("father(joe,john)")
Did somebody face the same issue, and do you know how to solve the problem?

Thank you in advance for your help :)

Here are the versions of my environment:
Ubuntu 20.04.5 LTS
pyswip: 0.2.10
swi-prolog: 9.0.0 for x86_64-linux
popper-ilp: git+https://github.com/logic-and-learning-lab/Popper@d85f5b906402d1cc62d75f5da6e48153727732ea

fyi, I've just reported this issue to https://github.com/yuce/pyswip/pull/93 as well

**Comment by ramparany** [comment]
swi-prolog developpers have published a patch on their web site that solved my problem. I'll give it in a similar issue that I just discovered this morning :)

**Comment by JennieZ98** [comment]
can u share the patch, thx!
