### ISSUE TITLE
Can Popper performs incrementally learning?

### ISSUE THREAD

**Issue by Zhang-Liao** [logic-and-learning-lab/Popper#58]
Dear developers,

I am trying to find a state-of-the-art ILP system for incremental learning. As far as I know, Popper is a state-of-the-art system. But I cannot understand whether it can perform incremental learning from the manual.

If it cannot, would you like to suggest me another state-of-the-art ILP system for incremental learning?

**Comment by andrewcropper** [comment]
What precisely do you mean by incremental learning? Learning different tasks incrementally?

**Comment by Zhang-Liao** [comment]
I am sorry for my unclearness. I think incremental learning is equal to life-long learning.
For a sequence of examples E1, E2,...En. We input examples one by one. First, learn a model for E1. If we input E2, then update the original model. We can repeatedly input a new example and update the original model.
That is what I mean. As far as I know, ILP is suitable for such tasks,

**Comment by Zhang-Liao** [comment]
There should be only one task

**Comment by andrewcropper** [comment]
Ah yes, I understand. That feature is not currently implemented in Popper but should be straightforward to implement. We will soon release a new version of Popper. We could try to include that feature in the release. Can you email me at ***@***.*** ? It might be easier to discuss this feature via email.
