### ISSUE TITLE
`explain` always true when invoked from commandline

### ISSUE THREAD

**Issue by tomsilver** [logic-and-learning-lab/Popper#64]
Looking here:
```python
parser.add_argument('--explain', default=True, action='store_true', help='explain')
```

Since `default=True`, `args.explain` will always be `True`, I think, even if `--explain` is not given.

I noticed this because of a discrepancy between running popper from the command line vs. running from another python program. The former was much faster than the latter, and it was because `explain` was true in the former but not the latter.

Btw, what does `explain` mean?

**Comment by andrewcropper** [comment]
fixed by enabling `explain` by default https://github.com/logic-and-learning-lab/Popper/commit/1c69be11ff5313f28fec6a57520029589fd6d278

the `explain` setting tells Popper to find the minimal unsatisfiable core of a totally incomplete program (a program that does not cover any positive examples)
