### ISSUE TITLE
Possible optimization (if not a bug): should the sub programs in the explainer also follow the constraint?

### ISSUE THREAD

**Issue by yangdinglou** [logic-and-learning-lab/Popper#67]
Hi Andrew,

Not sure if I understand correctly, but currently the `subprog`s generated by the explainer contain the ones which don't satisfy things like `non_datalog.` Is it true that they should be pruned?

**Comment by andrewcropper** [comment]
Yes, that is true, it prunes programs that do not necessarily obey the constraints. 

Kind regards,

Andrew
