### ISSUE TITLE
Remove renaming redundancies in the hypothesis space

### ISSUE THREAD

**Issue by andrewcropper** [logic-and-learning-lab/Popper#7]
The Alan ASP program generator is non-optimal. For instance, Alan will generate this program, where the last two rules are equivalent after renaming the variables:

```
f(A) :- head(A,B),even(B),odd(B)
f(A) :- tail(A,B),f(B)
f(A) :- tail(A,B),tail(B,C),f(C)
f(A) :- tail(A,C),tail(C,B),f(B)
```

Likewise in the `robots-linear` problem, Alan generates this solution:

```
f(A,B):-right(A,D),right(C,E),right(D,C),right(E,B).
f(A,B):-right(A,D),right(C,B),right(D,E),right(E,C).
f(A,B):-right(A,E),right(C,B),right(D,C),right(E,D).
f(A,B):-right(A,E),right(C,D),right(D,B),right(E,C).
f(A,B):-right(A,C),right(C,D),right(D,E),right(E,B).
f(A,B):-right(A,C),right(C,E),right(D,B),right(E,D).
```

In the `sorted` problem, Alan generates this solution:
```
f(A) :- tail(A,B),empty(B).
f(A) :- head(A,C),tail(A,D),head(D,B),gt(B,C),f(D).
f(A) :- head(A,B),tail(A,D),head(D,C),gt(C,B),f(D).
```
In the `trains` problem, Alan generates this solution:

```f(A):-circle(B),circle(C),has_load(A,B),has_load(A,C).```

We need to improve the ALAN encoding to reduce the number of redundant programs.

**Comment by rolfmorel** [comment]
The complete subsumption checking will prune all variants as soon as one of them has been tested and has failed.

**Comment by andrewcropper** [comment]
> The complete subsumption checking will prune all variants as soon as one of them has been tested and has failed.

The encoding should not generate the programs, regardless of seen failures.

**Comment by rolfmorel** [comment]
I already thought about that. I don't think it is going to work out, as you
can use such an encoding to solve graph isomorphism. It might be worthwhile
to actually show this by giving the reduction algorithm.

My intuition is that if it is possible it is going to blow up the size of
the encoding, like in going from lambda calculus (which has variables) to
combinatory logic (which has no variables).

**Comment by andrewcropper** [comment]
Issue is slightly mitigated with changes #9 #13 . 

But it would still be nice to push these changes to the ASP solver.
