### ISSUE TITLE
Maybe a bug in Popper/bin /popper-ilp

### ISSUE THREAD

**Issue by Zhang-Liao** [logic-and-learning-lab/Popper#80]
If I run `pip install git+https://github.com/logic-and-learning-lab/Popper@main` and execute `popper-ilp` in bash, the following error will occur.
```
XXX:~$ popper-ilp
Traceback (most recent call last):
  File "/XXX/conda/bin/popper-ilp", line 3, in <module>
    from popper.util import Settings, print_prog_score
ImportError: cannot import name 'print_prog_score' from 'popper.util' (/XXX/conda/lib/python3.11/site-packages/popper/util.py)
```
 The error seems to be caused by the file Popper/bin /popper-ilp. It uses `from popper.util import Settings, print_prog_score` but popper.py uses `from popper.util import Settings`. I remove the error after changing some lines of Popper/bin /popper-ilp and obtain a new file popper-ilp-new.

```
diff popper-ilp-new popper-ilp-old 
3c3
< from popper.util import Settings
---
> from popper.util import Settings, print_prog_score
10c10
<         settings.print_prog_score(prog, score)
---
>         print_prog_score(prog, score, settings.noisy)
15d14
< 
```

**Comment by andrewcropper** [comment]
Thanks! That is a bug. I will fix it.

**Comment by andrewcropper** [comment]
That should be fixed now (in `main` branch). Thanks!
