### ISSUE TITLE
Wrong pip version

### ISSUE THREAD

**Issue by Timisorean** [logic-and-learning-lab/Popper#82]
Hey! When installing Popper through pip and listing the version, it always gives me version 2.0.0:

```
Package          Version
---------------- --------
....
popper-ilp       2.0.0
...
```

Is this expected or should the pip version match the actual version 4.1.1. ?

Here the current setup.py:

```python
....
setuptools.setup(
    name="popper-ilp",
    version="2.0.0",                        # Update this for every new version
    author="Andrew Cropper",
    author_email="andrew.cropper@cs.ox.ac.uk",
...
```

**Comment by andrewcropper** [comment]
Thanks, that is a mistake. I completely forgot about that pip package. Thanks for letting me know!

**Comment by andrewcropper** [comment]
That should be fixed now (in `main` branch). Thanks! I also deleted PyPI package as I do not maintain it.
