### ISSUE TITLE
some questions pls

### ISSUE THREAD

**Issue by i-am-neo** [logic-and-learning-lab/Popper#88]
Hello @andrewcropper, thanks for sharing your work.  I'm looking to try Popper and have some questions that I haven't found answers from closed issues; I hope you can help.

1. If I provide solely positive examples, ie. a blank bk.pl and bias.pl, could Popper find a solution based on available/"core" swipl library?
  for example:
  
  exs.pl:
> pos( f([], []) ).
pos( f([1, 2, 3, 4, 5], [5,4,3,2,1]) ).
pos( f(['a', 'b', 'c', 'd', 'e'], ['e', 'd', 'c', 'b', 'a]) ).

  bias.pl:

> head_pred(f,2).

2. Can Popper propose solutions if the bias.pl file contain clauses superfluous to the problem at hand?  Put another way, if I do not know in advance what to include in the search space, and do not narrow it down, can Popper still propose solutions?  I am interested in incremental learning, as asked [here](https://github.com/logic-and-learning-lab/Popper/issues/58#issuecomment-1350914084).

3. If Popper cannot find any solutions, how best to figure out what could help it find a solution - ie. how do I know to add to examples versus the bias file? 

I'm happy to email you instead.
Many thanks in advance.

ps. I would've tried some of the above but am [waiting](https://github.com/SWI-Prolog/packages-swipy/issues/13#issue-2366860206) for some help in installing janus-swi, which seems to be a pre-requisite.

**Comment by andrewcropper** [comment]
Hi,

1. No, you need to provide a bias file to tell Popper which relations it
can use. Popper should be able to use relations built-in to Prolog.

2. Yes, but if you provide too many (thousands) then Popper will greatly
struggle.

3. There is no clear answer to this question. My usual approach is to find
a simple toy example and to make sure that you can write the corresponding
Prolog program and to  check that the bias is sufficient to learn that
program. Also, look at the examples in the repo for guidance.

Kind regards,

Andrew
