### ISSUE TITLE
meta-predicates

### ISSUE THREAD

**Issue by i-am-neo** [logic-and-learning-lab/Popper#91]
More a question.  Are meta-predicates supported in Popper?

Thanks.

**Comment by andrewcropper** [comment]
Hi,

Can you expand on what you mean by a meta-predicate?

**Comment by i-am-neo** [comment]
Hi @andrewcropper , like

> maplist(:Goal, +List1, ?List2)

where I can pass in another pedicate for 

> :Goal

Thank you.

**Comment by andrewcropper** [comment]
Unfortunately, the current code does not support such meta-predicates.  

However, a variant of the Hopper system (https://www.ijcai.org/proceedings/2022/0378.pdf) is available here:  https://github.com/celinehocquette/ijcai24-stevie

However, it greatly differs from the main Popper repository and is quite outdated.

**Comment by i-am-neo** [comment]
Thank you.  Are there other significant changes to Stevie apart from updating the Popper version?  Ie., if I use the current version of Popper, the examples in Stevie should still "work?"

**Comment by andrewcropper** [comment]
Hi,

All the examples that do not require meta-predicates will work.

Kind regards,

Andrew
