### ISSUE TITLE
how do you translate the ARC-AGI training examples into ILP background and example ?

### ISSUE THREAD

**Issue by zdx3578** [logic-and-learning-lab/Popper#93]
and how to set ARC-AGI  false example in ILP;

thanks very much !

**Comment by zdx3578** [comment]
abstract resource https://github.com/you68681/GPAR/tree/main/ARC-PDDL

**Comment by andrewcropper** [comment]
I am sorry again but I do not understand the question, or why you have linked to the GPAR repository.

Are you asking how can you use Popper on the ARC dataset?  If so, we describe one approach in this paper (https://arxiv.org/pdf/2408.12212). However, there are probably far better ways to do it.

**Comment by zdx3578** [comment]
yes ,  use Popper on the ARC dataset ,  in the paper (https://arxiv.org/pdf/2408.12212). how use is  not clear

**Comment by andrewcropper** [comment]
Can you please email me (andrew.cropper@cs.ox.ac.uk)? I can share all the data from that paper with you.
